#!/usr/bin/env python3
"""
evidence_collector.py
Automated Compliance Evidence Collection & Cataloging
Author: Zeshan Ahmad | github.com/cyberzeshan

Collects, hashes, timestamps, and catalogs compliance evidence artifacts from
multiple sources: config files, API snapshots, screenshots, and log exports.
Produces a signed evidence package with chain-of-custody metadata for auditors.

Usage:
    python3 evidence_collector.py --config config.yaml --output-dir ./evidence_package
"""

import os
import json
import hashlib
import shutil
import argparse
import logging
from datetime import datetime, timezone
from dataclasses import dataclass, field, asdict
from typing import List, Optional, Dict, Any
from pathlib import Path
from enum import Enum

logging.basicConfig(level=logging.INFO, format='%(asctime)s [%(levelname)s] %(message)s')
logger = logging.getLogger(__name__)


class EvidenceType(Enum):
    SCREENSHOT = "screenshot"
    LOG_EXPORT = "log_export"
    CONFIG_SNAPSHOT = "config_snapshot"
    POLICY_DOCUMENT = "policy_document"
    SCAN_REPORT = "scan_report"
    ACCESS_LIST = "access_list"
    TICKET_EXPORT = "ticket_export"
    ATTESTATION = "attestation"
    API_RESPONSE = "api_response"


class CollectionStatus(Enum):
    COLLECTED = "COLLECTED"
    MISSING = "MISSING"
    STALE = "STALE"
    ERROR = "ERROR"


@dataclass
class EvidenceItem:
    evidence_id: str
    title: str
    evidence_type: EvidenceType
    framework: str
    control_ref: str
    status: CollectionStatus
    file_path: Optional[str] = None
    sha256_hash: Optional[str] = None
    source_system: Optional[str] = None
    collected_by: Optional[str] = None
    collection_notes: Optional[str] = None
    expiry_date: Optional[str] = None
    collected_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())


class EvidenceCollector:
    """
    Collects, hashes, and catalogs compliance evidence artifacts.
    Extend _collect_* methods to query your live systems (AWS, Azure, Okta, etc.).
    """

    def __init__(self, config: dict, output_dir: str = "./evidence_package"):
        self.config = config
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.items: List[EvidenceItem] = []
        self.collection_timestamp = datetime.now(timezone.utc).isoformat()
        self.collector_id = config.get("collector", {}).get("identity", "compliance-automation")

    # ── Utility helpers ───────────────────────────────────────────────────────

    def _sha256_file(self, path: Path) -> str:
        h = hashlib.sha256()
        with open(path, "rb") as f:
            for chunk in iter(lambda: f.read(8192), b""):
                h.update(chunk)
        return h.hexdigest()

    def _sha256_string(self, content: str) -> str:
        return hashlib.sha256(content.encode()).hexdigest()

    def _save_json_artifact(self, filename: str, data: Any) -> Path:
        dest = self.output_dir / filename
        with open(dest, "w") as f:
            json.dump(data, f, indent=2)
        return dest

    def _copy_artifact(self, source: str, dest_name: str) -> Optional[Path]:
        src = Path(source)
        if not src.exists():
            return None
        dest = self.output_dir / dest_name
        shutil.copy2(src, dest)
        return dest

    def _register(self, item: EvidenceItem):
        self.items.append(item)
        symbol = "✅" if item.status == CollectionStatus.COLLECTED else (
            "⚠️" if item.status == CollectionStatus.STALE else "❌"
        )
        logger.info(f"{symbol} [{item.framework}] {item.control_ref}: {item.title}")

    # ── IAM / Access Evidence ─────────────────────────────────────────────────

    def collect_mfa_policy_snapshot(self):
        """Collect MFA enforcement policy configuration as evidence"""
        iam_cfg = self.config.get("iam", {})
        evidence_data = {
            "collection_timestamp": self.collection_timestamp,
            "mfa_enforced_for_admins": iam_cfg.get("mfa_enforced_for_admins"),
            "mfa_enforced_for_all_users": iam_cfg.get("mfa_enforced_for_all_users"),
            "privileged_accounts_without_mfa": iam_cfg.get("privileged_accounts_without_mfa", []),
            "mfa_policy_source": iam_cfg.get("mfa_policy_source", "IAM Policy"),
            "note": "Generated by evidence_collector.py — replace with live API call",
        }
        dest = self._save_json_artifact("mfa_policy_snapshot.json", evidence_data)
        file_hash = self._sha256_file(dest)

        self._register(EvidenceItem(
            evidence_id="EVD-IAM-001",
            title="MFA Enforcement Policy Snapshot",
            evidence_type=EvidenceType.CONFIG_SNAPSHOT,
            framework="SOC 2 / PCI-DSS",
            control_ref="CC6.1 / PCI Req 8",
            status=CollectionStatus.COLLECTED,
            file_path=str(dest),
            sha256_hash=file_hash,
            source_system=iam_cfg.get("mfa_policy_source", "IAM"),
            collected_by=self.collector_id,
            collection_notes="IAM MFA configuration snapshot",
        ))

    def collect_user_access_list(self):
        """Collect current user access list (all users + roles)"""
        users = self.config.get("iam", {}).get("user_roster", [])
        if not users:
            # Generate sample structure when no live data provided
            users = [
                {"username": "example.user@company.com", "role": "read-only", "mfa_enabled": True,
                 "last_login": "2026-05-15", "status": "active"},
            ]
            status = CollectionStatus.STALE
            notes = "Sample data — connect to directory (Okta/AD) for live export"
        else:
            status = CollectionStatus.COLLECTED
            notes = "Exported from identity provider"

        evidence_data = {
            "collection_timestamp": self.collection_timestamp,
            "total_users": len(users),
            "users": users,
        }
        dest = self._save_json_artifact("user_access_list.json", evidence_data)
        file_hash = self._sha256_file(dest)

        self._register(EvidenceItem(
            evidence_id="EVD-IAM-002",
            title="User Access List & Role Assignments",
            evidence_type=EvidenceType.ACCESS_LIST,
            framework="SOC 2 / ISO 27001 / PCI-DSS",
            control_ref="CC6.2 / A.5.15 / PCI Req 7",
            status=status,
            file_path=str(dest),
            sha256_hash=file_hash,
            source_system="Identity Provider",
            collected_by=self.collector_id,
            collection_notes=notes,
            expiry_date="90 days",
        ))

    def collect_privileged_access_review(self):
        """Collect privileged account review evidence"""
        last_review = self.config.get("iam", {}).get("last_privileged_review_date", "")
        reviewer = self.config.get("iam", {}).get("last_privileged_review_by", "")
        privileged_accounts = self.config.get("iam", {}).get("privileged_account_list", [])

        evidence_data = {
            "collection_timestamp": self.collection_timestamp,
            "last_review_date": last_review,
            "reviewed_by": reviewer,
            "privileged_accounts_reviewed": len(privileged_accounts),
            "accounts": privileged_accounts,
        }
        dest = self._save_json_artifact("privileged_access_review.json", evidence_data)
        file_hash = self._sha256_file(dest)

        status = CollectionStatus.COLLECTED if last_review else CollectionStatus.MISSING

        self._register(EvidenceItem(
            evidence_id="EVD-IAM-003",
            title="Privileged Account Access Review",
            evidence_type=EvidenceType.ACCESS_LIST,
            framework="SOC 2 / PCI-DSS",
            control_ref="CC6.3 / PCI Req 7.2",
            status=status,
            file_path=str(dest),
            sha256_hash=file_hash,
            source_system="IAM / ITSM",
            collected_by=self.collector_id,
            collection_notes=f"Reviewed by {reviewer or 'UNKNOWN'} on {last_review or 'NOT RECORDED'}",
        ))

    # ── Monitoring / SIEM Evidence ────────────────────────────────────────────

    def collect_siem_configuration(self):
        """Collect SIEM configuration and alert rules summary"""
        monitoring = self.config.get("monitoring", {})
        evidence_data = {
            "collection_timestamp": self.collection_timestamp,
            "siem_platform": monitoring.get("siem_platform", "Unknown"),
            "siem_enabled": monitoring.get("siem_enabled"),
            "active_alert_rules": monitoring.get("active_alert_rules"),
            "log_retention_days": monitoring.get("log_retention_days"),
            "log_sources_connected": monitoring.get("log_sources", []),
            "24_7_monitoring": monitoring.get("24_7_monitoring", False),
        }
        dest = self._save_json_artifact("siem_configuration.json", evidence_data)
        file_hash = self._sha256_file(dest)

        self._register(EvidenceItem(
            evidence_id="EVD-MON-001",
            title="SIEM Configuration & Alert Rules Summary",
            evidence_type=EvidenceType.CONFIG_SNAPSHOT,
            framework="SOC 2 / ISO 27001 / PCI-DSS",
            control_ref="CC7.2 / A.8.16 / PCI Req 10",
            status=CollectionStatus.COLLECTED,
            file_path=str(dest),
            sha256_hash=file_hash,
            source_system=monitoring.get("siem_platform", "SIEM"),
            collected_by=self.collector_id,
            collection_notes="SIEM platform configuration snapshot",
        ))

    def collect_log_retention_evidence(self):
        """Collect log retention policy configuration"""
        monitoring = self.config.get("monitoring", {})
        retention_days = monitoring.get("log_retention_days", 0)

        evidence_data = {
            "collection_timestamp": self.collection_timestamp,
            "retention_policy_days": retention_days,
            "log_archive_location": monitoring.get("log_archive_location", ""),
            "immutable_storage": monitoring.get("immutable_log_storage", False),
            "compliance_note": (
                "COMPLIANT" if retention_days >= 365
                else f"NON-COMPLIANT — {retention_days} days (minimum: 365)"
            ),
        }
        dest = self._save_json_artifact("log_retention_policy.json", evidence_data)
        file_hash = self._sha256_file(dest)

        status = CollectionStatus.COLLECTED if retention_days >= 365 else CollectionStatus.STALE

        self._register(EvidenceItem(
            evidence_id="EVD-MON-002",
            title="Log Retention Policy Evidence",
            evidence_type=EvidenceType.CONFIG_SNAPSHOT,
            framework="SOC 2 / PCI-DSS",
            control_ref="CC7.2 / PCI Req 10.7",
            status=status,
            file_path=str(dest),
            sha256_hash=file_hash,
            source_system="Logging Infrastructure",
            collected_by=self.collector_id,
            collection_notes=f"Retention: {retention_days} days",
        ))

    # ── Vulnerability Management Evidence ─────────────────────────────────────

    def collect_vuln_scan_reports(self):
        """Collect or reference vulnerability scan report artifacts"""
        vuln_cfg = self.config.get("vulnerability_mgmt", {})
        scan_reports = vuln_cfg.get("scan_report_paths", [])

        collected_reports = []
        for report_path in scan_reports:
            dest = self._copy_artifact(report_path, Path(report_path).name)
            if dest:
                collected_reports.append({
                    "original_path": report_path,
                    "archived_path": str(dest),
                    "sha256": self._sha256_file(dest),
                })

        # Collect metadata even when no actual files are provided
        evidence_data = {
            "collection_timestamp": self.collection_timestamp,
            "scan_tool": vuln_cfg.get("scan_tool", ""),
            "scan_frequency_days": vuln_cfg.get("scan_frequency_days"),
            "last_scan_date": vuln_cfg.get("last_scan_date", ""),
            "critical_open": vuln_cfg.get("open_critical_count", 0),
            "high_open": vuln_cfg.get("open_high_count", 0),
            "reports_collected": len(collected_reports),
            "reports": collected_reports,
        }
        dest = self._save_json_artifact("vulnerability_scan_summary.json", evidence_data)
        file_hash = self._sha256_file(dest)

        status = CollectionStatus.COLLECTED if vuln_cfg.get("last_scan_date") else CollectionStatus.MISSING

        self._register(EvidenceItem(
            evidence_id="EVD-VULN-001",
            title="Vulnerability Scan Reports Summary",
            evidence_type=EvidenceType.SCAN_REPORT,
            framework="SOC 2 / PCI-DSS / ISO 27001",
            control_ref="CC7.3 / PCI Req 11 / A.8.8",
            status=status,
            file_path=str(dest),
            sha256_hash=file_hash,
            source_system=vuln_cfg.get("scan_tool", "Vulnerability Scanner"),
            collected_by=self.collector_id,
            collection_notes=f"Last scan: {vuln_cfg.get('last_scan_date', 'UNKNOWN')}",
        ))

    # ── Incident Response Evidence ────────────────────────────────────────────

    def collect_ir_plan_evidence(self):
        """Collect incident response plan and testing artifacts"""
        ir_cfg = self.config.get("incident_response", {})
        ir_doc_path = ir_cfg.get("ir_plan_path", "")

        evidence_data = {
            "collection_timestamp": self.collection_timestamp,
            "ir_plan_documented": ir_cfg.get("ir_plan_documented"),
            "ir_plan_version": ir_cfg.get("ir_plan_version", ""),
            "ir_plan_last_reviewed": ir_cfg.get("ir_plan_last_reviewed", ""),
            "last_tabletop_date": ir_cfg.get("last_tabletop_date", ""),
            "last_tabletop_participants": ir_cfg.get("last_tabletop_participants", []),
            "incident_tracking_tool": ir_cfg.get("incident_tracking_tool", ""),
        }

        if ir_doc_path:
            copied = self._copy_artifact(ir_doc_path, "ir_plan." + Path(ir_doc_path).suffix.lstrip("."))
            if copied:
                evidence_data["ir_plan_file_archived"] = str(copied)
                evidence_data["ir_plan_sha256"] = self._sha256_file(copied)

        dest = self._save_json_artifact("ir_plan_evidence.json", evidence_data)
        file_hash = self._sha256_file(dest)
        status = CollectionStatus.COLLECTED if ir_cfg.get("ir_plan_documented") else CollectionStatus.MISSING

        self._register(EvidenceItem(
            evidence_id="EVD-IR-001",
            title="Incident Response Plan & Tabletop Evidence",
            evidence_type=EvidenceType.POLICY_DOCUMENT,
            framework="SOC 2 / ISO 27001 / PCI-DSS",
            control_ref="CC7.4 / A.5.26 / PCI Req 12.10",
            status=status,
            file_path=str(dest),
            sha256_hash=file_hash,
            source_system="GRC / Document Management",
            collected_by=self.collector_id,
            collection_notes=(
                f"IR plan v{ir_cfg.get('ir_plan_version', 'N/A')}; "
                f"last tabletop: {ir_cfg.get('last_tabletop_date', 'UNKNOWN')}"
            ),
        ))

    # ── Policy & Training Evidence ────────────────────────────────────────────

    def collect_security_training_evidence(self):
        """Collect security awareness training completion records"""
        training_cfg = self.config.get("training", {})
        evidence_data = {
            "collection_timestamp": self.collection_timestamp,
            "training_platform": training_cfg.get("platform", ""),
            "training_period": training_cfg.get("training_period", ""),
            "total_staff": training_cfg.get("total_staff", 0),
            "completed": training_cfg.get("completed", 0),
            "completion_rate_pct": training_cfg.get("pct_completed", 0),
            "phishing_simulation_results": training_cfg.get("phishing_sim_click_rate_pct", None),
            "non_compliant_users": training_cfg.get("non_compliant_users", []),
        }
        dest = self._save_json_artifact("security_training_records.json", evidence_data)
        file_hash = self._sha256_file(dest)
        pct = training_cfg.get("pct_completed", 0)
        status = CollectionStatus.COLLECTED if pct >= 90 else (
            CollectionStatus.STALE if pct > 0 else CollectionStatus.MISSING
        )

        self._register(EvidenceItem(
            evidence_id="EVD-TRN-001",
            title="Security Awareness Training Completion Records",
            evidence_type=EvidenceType.ATTESTATION,
            framework="ISO 27001 / SOC 2 / PCI-DSS",
            control_ref="A.6.3 / CC1.4 / PCI Req 12.6",
            status=status,
            file_path=str(dest),
            sha256_hash=file_hash,
            source_system=training_cfg.get("platform", "LMS"),
            collected_by=self.collector_id,
            collection_notes=f"Completion: {pct}%",
        ))

    # ── Encryption Evidence ───────────────────────────────────────────────────

    def collect_encryption_configuration(self):
        """Collect encryption at rest and in transit configuration"""
        dp_cfg = self.config.get("data_protection", {})
        evidence_data = {
            "collection_timestamp": self.collection_timestamp,
            "encryption_at_rest": dp_cfg.get("encryption_at_rest"),
            "encryption_algorithm_at_rest": dp_cfg.get("encryption_algorithm", "AES-256"),
            "tls_version_enforced": dp_cfg.get("tls_version", "TLS 1.3"),
            "weak_protocols_disabled": dp_cfg.get("weak_protocols_disabled"),
            "key_management_system": dp_cfg.get("key_management_system", ""),
            "key_rotation_days": dp_cfg.get("key_rotation_days", None),
            "unencrypted_stores": dp_cfg.get("unencrypted_data_stores", []),
        }
        dest = self._save_json_artifact("encryption_configuration.json", evidence_data)
        file_hash = self._sha256_file(dest)

        status = (
            CollectionStatus.COLLECTED
            if dp_cfg.get("encryption_at_rest") and not dp_cfg.get("unencrypted_data_stores")
            else CollectionStatus.STALE
        )

        self._register(EvidenceItem(
            evidence_id="EVD-CRYPT-001",
            title="Encryption Configuration (At Rest & In Transit)",
            evidence_type=EvidenceType.CONFIG_SNAPSHOT,
            framework="SOC 2 / PCI-DSS / ISO 27001",
            control_ref="CC6.1 / PCI Req 3-4 / A.8.24",
            status=status,
            file_path=str(dest),
            sha256_hash=file_hash,
            source_system=dp_cfg.get("key_management_system", "KMS"),
            collected_by=self.collector_id,
            collection_notes=f"At-rest: {dp_cfg.get('encryption_algorithm', 'AES-256')}; "
                             f"in-transit: {dp_cfg.get('tls_version', 'TLS 1.3')}",
        ))

    # ── Change Management Evidence ────────────────────────────────────────────

    def collect_change_management_evidence(self):
        """Collect sample of approved change tickets as evidence"""
        cm_cfg = self.config.get("change_management", {})
        evidence_data = {
            "collection_timestamp": self.collection_timestamp,
            "change_tracking_tool": cm_cfg.get("tool", ""),
            "sample_period": cm_cfg.get("sample_period", "last 90 days"),
            "total_changes": cm_cfg.get("total_changes_in_period", 0),
            "pct_with_approval": cm_cfg.get("pct_changes_with_approval", 0),
            "pct_with_testing_evidence": cm_cfg.get("pct_changes_with_test_evidence", 0),
            "emergency_changes": cm_cfg.get("emergency_changes_in_period", 0),
            "sample_tickets": cm_cfg.get("sample_change_tickets", []),
        }
        dest = self._save_json_artifact("change_management_evidence.json", evidence_data)
        file_hash = self._sha256_file(dest)

        status = (
            CollectionStatus.COLLECTED
            if cm_cfg.get("pct_changes_with_approval", 0) >= 95
            else CollectionStatus.STALE
        )

        self._register(EvidenceItem(
            evidence_id="EVD-CHG-001",
            title="Change Management Ticket Sample & Approval Evidence",
            evidence_type=EvidenceType.TICKET_EXPORT,
            framework="SOC 2 / PCI-DSS",
            control_ref="CC8.1 / PCI Req 6.5",
            status=status,
            file_path=str(dest),
            sha256_hash=file_hash,
            source_system=cm_cfg.get("tool", "ITSM"),
            collected_by=self.collector_id,
            collection_notes=f"Approval rate: {cm_cfg.get('pct_changes_with_approval', 0)}%",
        ))

    # ── Vendor Risk Evidence ──────────────────────────────────────────────────

    def collect_vendor_risk_evidence(self):
        """Collect vendor/TPSP inventory and contract status"""
        vr_cfg = self.config.get("vendor_risk", {})
        evidence_data = {
            "collection_timestamp": self.collection_timestamp,
            "vendor_inventory_count": vr_cfg.get("vendor_count", 0),
            "vendors_with_contracts": vr_cfg.get("pct_vendors_with_contracts", 0),
            "last_vendor_review_date": vr_cfg.get("last_review_date", ""),
            "high_risk_vendors": vr_cfg.get("high_risk_vendors", []),
            "vendor_list": vr_cfg.get("vendor_list", []),
        }
        dest = self._save_json_artifact("vendor_risk_inventory.json", evidence_data)
        file_hash = self._sha256_file(dest)

        status = (
            CollectionStatus.COLLECTED
            if vr_cfg.get("vendor_count", 0) > 0 and vr_cfg.get("last_review_date")
            else CollectionStatus.MISSING
        )

        self._register(EvidenceItem(
            evidence_id="EVD-VR-001",
            title="Vendor / TPSP Risk Inventory & Contract Status",
            evidence_type=EvidenceType.ACCESS_LIST,
            framework="SOC 2 / ISO 27001 / PCI-DSS",
            control_ref="CC9.1 / A.5.19 / PCI Req 12.8",
            status=status,
            file_path=str(dest),
            sha256_hash=file_hash,
            source_system="GRC Platform / Procurement",
            collected_by=self.collector_id,
            collection_notes=f"{vr_cfg.get('vendor_count', 0)} vendors; "
                             f"{vr_cfg.get('pct_vendors_with_contracts', 0)}% contracted",
        ))

    # ── Runner & Package Generation ───────────────────────────────────────────

    def run_all_collections(self) -> dict:
        logger.info("Starting evidence collection run...")

        collectors = [
            self.collect_mfa_policy_snapshot,
            self.collect_user_access_list,
            self.collect_privileged_access_review,
            self.collect_siem_configuration,
            self.collect_log_retention_evidence,
            self.collect_vuln_scan_reports,
            self.collect_ir_plan_evidence,
            self.collect_security_training_evidence,
            self.collect_encryption_configuration,
            self.collect_change_management_evidence,
            self.collect_vendor_risk_evidence,
        ]

        for collector in collectors:
            try:
                collector()
            except Exception as e:
                logger.error(f"Error in {collector.__name__}: {e}")

        manifest = self._generate_manifest()
        manifest_path = self.output_dir / "EVIDENCE_MANIFEST.json"
        with open(manifest_path, "w") as f:
            json.dump(manifest, f, indent=2)

        logger.info(f"Evidence package written to: {self.output_dir}")
        return manifest

    def _generate_manifest(self) -> dict:
        collected = sum(1 for i in self.items if i.status == CollectionStatus.COLLECTED)
        missing = sum(1 for i in self.items if i.status == CollectionStatus.MISSING)
        stale = sum(1 for i in self.items if i.status == CollectionStatus.STALE)

        # Build manifest hash over all collected file hashes
        all_hashes = sorted([i.sha256_hash for i in self.items if i.sha256_hash])
        package_hash = hashlib.sha256("\n".join(all_hashes).encode()).hexdigest()

        return {
            "manifest_metadata": {
                "collection_timestamp": self.collection_timestamp,
                "collector_version": "2.0.0",
                "collector_id": self.collector_id,
                "output_directory": str(self.output_dir),
                "package_integrity_hash": package_hash,
            },
            "summary": {
                "total_evidence_items": len(self.items),
                "collected": collected,
                "stale_or_partial": stale,
                "missing": missing,
                "collection_completeness_pct": round(collected / len(self.items) * 100, 1) if self.items else 0,
            },
            "evidence_items": [
                {
                    **{k: (v.value if isinstance(v, Enum) else v) for k, v in asdict(item).items()},
                }
                for item in self.items
            ],
        }


def _load_config(path: str) -> dict:
    import yaml
    with open(path) as f:
        return yaml.safe_load(f)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Compliance evidence collector and packager")
    parser.add_argument("--config", help="Path to YAML config file")
    parser.add_argument("--output-dir", default="./evidence_package", help="Output directory for evidence package")
    args = parser.parse_args()

    if args.config:
        config = _load_config(args.config)
    else:
        config = {
            "collector": {"identity": "compliance-bot@company.com"},
            "iam": {
                "mfa_enforced_for_admins": True,
                "mfa_enforced_for_all_users": True,
                "privileged_accounts_without_mfa": [],
                "mfa_policy_source": "Okta IAM Policy",
                "last_privileged_review_date": "2026-05-01",
                "last_privileged_review_by": "security-team@company.com",
                "privileged_account_list": [
                    {"username": "admin.user", "role": "cloud-admin", "mfa": True},
                ],
                "user_roster": [],
            },
            "monitoring": {
                "siem_platform": "Splunk",
                "siem_enabled": True,
                "active_alert_rules": 87,
                "log_retention_days": 365,
                "log_sources": ["AWS CloudTrail", "Azure AD", "Firewall", "Endpoint"],
                "24_7_monitoring": True,
                "log_archive_location": "s3://company-compliance-logs",
                "immutable_log_storage": True,
            },
            "vulnerability_mgmt": {
                "scan_tool": "Tenable.io",
                "scan_frequency_days": 7,
                "last_scan_date": "2026-06-01",
                "open_critical_count": 0,
                "open_high_count": 3,
                "scan_report_paths": [],
            },
            "incident_response": {
                "ir_plan_documented": True,
                "ir_plan_version": "3.1",
                "ir_plan_last_reviewed": "2026-03-01",
                "last_tabletop_date": "2026-01-15",
                "last_tabletop_participants": ["security", "legal", "comms", "engineering"],
                "incident_tracking_tool": "Jira",
                "ir_plan_path": "",
            },
            "training": {
                "platform": "KnowBe4",
                "training_period": "Q1 2026",
                "total_staff": 200,
                "completed": 194,
                "pct_completed": 97,
                "phishing_sim_click_rate_pct": 2.1,
                "non_compliant_users": [],
            },
            "data_protection": {
                "encryption_at_rest": True,
                "encryption_algorithm": "AES-256-GCM",
                "tls_version": "TLS 1.3",
                "weak_protocols_disabled": True,
                "key_management_system": "AWS KMS",
                "key_rotation_days": 365,
                "unencrypted_data_stores": [],
            },
            "change_management": {
                "tool": "Jira",
                "sample_period": "last 90 days",
                "total_changes_in_period": 124,
                "pct_changes_with_approval": 100,
                "pct_changes_with_test_evidence": 98,
                "emergency_changes_in_period": 2,
                "sample_change_tickets": [],
            },
            "vendor_risk": {
                "vendor_count": 45,
                "pct_vendors_with_contracts": 100,
                "last_review_date": "2026-04-01",
                "high_risk_vendors": [],
                "vendor_list": [],
            },
        }

    collector = EvidenceCollector(config=config, output_dir=args.output_dir)
    manifest = collector.run_all_collections()

    print("\n" + "=" * 60)
    print("EVIDENCE COLLECTION COMPLETE")
    print("=" * 60)
    print(f"Items Collected:   {manifest['summary']['collected']}/{manifest['summary']['total_evidence_items']}")
    print(f"Completeness:      {manifest['summary']['collection_completeness_pct']}%")
    print(f"Missing:           {manifest['summary']['missing']}")
    print(f"Stale/Partial:     {manifest['summary']['stale_or_partial']}")
    print(f"Package Hash:      {manifest['manifest_metadata']['package_integrity_hash'][:16]}...")
    print(f"Output Directory:  {args.output_dir}")
    print("=" * 60)
